config/routes.rb
Rails.application.routes.draw do
  resources :events
  root to: 'home#show' 
  devise_for :users
  resources :users
  get 'users/profile'
  get 'users/profile', as: 'user_root'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  validates :email, :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout "events"

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
  end

  private
    def event_params
      params.require(:event).permit(:title, :date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/application/_header.html.slim
header.header
  .header__logo Events!

  nav.header__menu
    = link_to 'Home', root_path, class: 'header__link'
    = link_to 'Events', events_path, class: 'header__link header__link--main'

app/views/events/_form.html.slim
= form_with model: @event, class: 'form-new', local: true do |form|
    - if @event.errors.any?
      #error_explanation
        h2
          = pluralize(@event.errors.count, 'error')
          |  prohibited this event from being saved:
        ul
          - @event.errors.full_messages.each do |msg|
            li
              = msg
    .form-new__field
      = form.text_field :title, placeholder: 'Title'
    .form-new__field
      = form.text_field :description, placeholder: 'Title'
    .form-new__field
      = form.datetime_select :date
    .form-new__button
      = form.submit

app/views/events/edit.html.slim
h1
  | Edit event
= render 'form'

app/views/events/index.html.slim
h2 
  ' All events
ul.events-list
  -@events.each do |event|
    li.events-list__item
      = link_to event.title, event_path(event)
      = @event.date  
      .events-list__icons
      = link_to edit_event_path(event), class: 'events-list__icon' do
          = image_tag 'edit.svg'
      = link_to event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, id: 'delete-event', class: 'events-list__icon' do
        = image_tag 'delete.svg'

= link_to 'New event', new_event_path, class: 'button'

app/views/events/new.html.slim
h2 Add new event!
= render 'form'
= link_to events_path, class: 'back'
  =image_tag 'back.svg'

app/views/events/show.html.slim
.event
  .event__header
    .event__title
      | event: #{ @event.title }

    .group-buttons
      .group-buttons__but
        = link_to edit_event_path(params[:card_id], @event) do
          =image_tag 'edit.svg'
      .group-buttons__but
        = link_to event_path(params[:card_id], @event), method: :delete, data: { confirm: 'Are you sure?' } do
          =image_tag 'delete.svg'
  = @event.date
  .event__description
    = @event.description

app/views/home/show.html.slim
- if user_signed_in?
  span
    | Здравствуйте, #{current_user.email}
    <br>
  = link_to 'Выйти', destroy_user_session_path, :method => :delete
- else
  = link_to 'Войти', new_user_session_path
  | или #{link_to ' Зарегистрироваться', new_user_registration_path}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/events.html.slim
doctype html
html
  head
    title
      | Events!
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    =render 'header'

    main.content
      = yield

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-eval': 'false'

app/views/layouts/home.html.slim
doctype html
html
  head
    title
      | Events!
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    =render 'header'

    main.content
      = yield
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/users/profile.html.slim
.event
  .event__header
    .event__title
      | #{ @user.email }

    .group-buttons
      .group-buttons__but
        = link_to edit_user_path(params[:id], @event) do
          =image_tag 'edit.svg'
      .group-buttons__but
        = link_to 'New event', new_event_path, class: 'button'